const { defineConfig } = require("cypress");
const webpack = require("@cypress/webpack-preprocessor");
const preprocessor = require("@badeball/cypress-cucumber-preprocessor");

async function setupNodeEvents(on, config) {
  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await preprocessor.addCucumberPreprocessorPlugin(on, config);

  on(
    "file:preprocessor",
    webpack({
      webpackOptions: {
        resolve: {
          extensions: [".ts", ".js"],
        },
        module: {
          rules: [
            {
              test: /\.feature$/,
              use: [
                {
                  loader: "@badeball/cypress-cucumber-preprocessor/webpack",
                  options: config,
                },
              ],
            },
          ],
        },
      },
    })
  );

  return config;
}

module.exports = defineConfig({
  reporter: 'node_modules/mochawesome/src/mochawesome.js',
  reporterOptions: {
  reportFilename: "Bbc Sport",
  reportPageTitle: "Complete Test Report",
  reportPageFooter: "<p>Generated by Mochawesome</p>",
  reportDirClean: true,
  reportDir: 'reports',
  timestamp: "yyyy-mm-dd",
  consoleReporter: "spec",
  charts: true,
  code: true,
  cdn: false,
  overwrite: false,
  html: true,
  json: false,
  assertionStyle: "classic",
  },

  modifyObstructiveCode: false,
  video: true,
  videosFolder: '../../cypress/reports/videos',
  screenshotsFolder: '../../../../cypress/reports/screenshots',
  chromeWebSecurity: false,
  slowMo: 5000,

  e2e: {
    specPattern: "**/*.feature",
    supportFile: "cypress/support/e2e.js",
    setupNodeEvents,
  },
});